
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class menubar extends javax.swing.JFrame {

    /**
     * Creates new form menubar
     */
    public menubar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVentana = new javax.swing.JMenu();
        menuColores = new javax.swing.JMenu();
        itemMenuColorVentana1 = new javax.swing.JMenuItem();
        itemMenuColorVentana2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMenuSalir = new javax.swing.JMenuItem();
        MenuLabel = new javax.swing.JMenu();
        menuColoresLabel = new javax.swing.JMenu();
        itemMenuColorLabel1 = new javax.swing.JMenuItem();
        itemMenuColorLabel2 = new javax.swing.JMenuItem();
        menuImagen = new javax.swing.JMenu();
        itemMenuImagen1 = new javax.swing.JMenuItem();
        itemMenuImagen2 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        itemMenuCreador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuVentana.setText("Ventana");
        menuVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentanaActionPerformed(evt);
            }
        });

        menuColores.setText("Colores");

        itemMenuColorVentana1.setText("Color1");
        itemMenuColorVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorVentana1ActionPerformed(evt);
            }
        });
        menuColores.add(itemMenuColorVentana1);

        itemMenuColorVentana2.setText("Color2");
        menuColores.add(itemMenuColorVentana2);

        menuVentana.add(menuColores);
        menuVentana.add(jSeparator1);

        itemMenuSalir.setText("Salir");
        itemMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirActionPerformed(evt);
            }
        });
        menuVentana.add(itemMenuSalir);

        jMenuBar1.add(menuVentana);

        MenuLabel.setText("Label");

        menuColoresLabel.setText("Colores");

        itemMenuColorLabel1.setText("Color1");
        itemMenuColorLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorLabel1ActionPerformed(evt);
            }
        });
        menuColoresLabel.add(itemMenuColorLabel1);

        itemMenuColorLabel2.setText("Color2");
        menuColoresLabel.add(itemMenuColorLabel2);

        MenuLabel.add(menuColoresLabel);

        menuImagen.setText("Imagenes");

        itemMenuImagen1.setText("Imagenes1");
        itemMenuImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuImagen1ActionPerformed(evt);
            }
        });
        menuImagen.add(itemMenuImagen1);

        itemMenuImagen2.setText("Imagenes2");
        menuImagen.add(itemMenuImagen2);

        MenuLabel.add(menuImagen);

        jMenuBar1.add(MenuLabel);

        menuAbout.setText("About");

        itemMenuCreador.setText("Creador");
        itemMenuCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCreadorActionPerformed(evt);
            }
        });
        menuAbout.add(itemMenuCreador);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(label)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(label)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuColorVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorVentana1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemMenuColorVentana1ActionPerformed

    private void menuVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentanaActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.decode("#99f00"));
    }//GEN-LAST:event_menuVentanaActionPerformed

    private void itemMenuColorLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorLabel1ActionPerformed
        // TODO add your handling code here:
        label.setOpaque(true);
        label.setBackground(Color.decode("#9F33FF"));
    }//GEN-LAST:event_itemMenuColorLabel1ActionPerformed

    private void itemMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemMenuSalirActionPerformed

    private void itemMenuCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCreadorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"sebitas");
    }//GEN-LAST:event_itemMenuCreadorActionPerformed

    private void itemMenuImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuImagen1ActionPerformed
        // TODO add your handling code here:
        ImageIcon nuevoIcono=new ImageIcon("src/icons/gatoo.jpg");
        label.setIcon(nuevoIcono);
    }//GEN-LAST:event_itemMenuImagen1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menubar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLabel;
    private javax.swing.JMenuItem itemMenuColorLabel1;
    private javax.swing.JMenuItem itemMenuColorLabel2;
    private javax.swing.JMenuItem itemMenuColorVentana1;
    private javax.swing.JMenuItem itemMenuColorVentana2;
    private javax.swing.JMenuItem itemMenuCreador;
    private javax.swing.JMenuItem itemMenuImagen1;
    private javax.swing.JMenuItem itemMenuImagen2;
    private javax.swing.JMenuItem itemMenuSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuColores;
    private javax.swing.JMenu menuColoresLabel;
    private javax.swing.JMenu menuImagen;
    private javax.swing.JMenu menuVentana;
    // End of variables declaration//GEN-END:variables
}
